### ISSUE TITLE
Isoseq-browser has no  content

### ISSUE THREAD

**Issue by jamescjc123** [goeckslab/isoseq-browser#2]
hi,
       the browser is  very useful, I want to try it. when I run Isoseq-browser by gene annotation and pickle file, the Isoseq-browser has no content. I want to know how to solve it? 
   
       the command is:
make run ANNOTATION_GTF=gencode.v25.annotation.gtf MATCHES_INPUT=mcf7_matchAnnot_results_download.pickle

       the message is:
source activate ib_env && PYTHONPATH=./dep:. bokeh serve --show browse.py --args --input mcf7_matchAnnot_results_download.pickle --anno gencode.v25.annotation.gtf
/share/work1/staff/chaijc/software/isoseq-browser/browse.py:210: SyntaxWarning: name 'opt' is used prior to global declaration
global tranNum, colorDF, chromosome, strand, opt
2017-02-13 15:08:41,662 Starting Bokeh server version 0.12.0
2017-02-13 15:08:41,676 Starting Bokeh server on port 5006 with applications at paths ['/browse']
2017-02-13 15:08:41,676 Starting Bokeh server with process id: 13254
/usr/bin/xdg-open: line 402: htmlview: command not found
2017-02-13 15:08:43,477 W-1002 (EMPTY_LAYOUT): Layout has no children: Column, ViewModel:Column, ref _id: a350ed0e-e460-4e6a-ae9a-0fc52b8dd41c
2017-02-13 15:08:43,494 200 GET /browse (127.0.0.1) 847.38ms

        thank you !

**Comment by jingyuanhu01** [comment]
Hi,

If the web browser does not open a web page automatically, open any web browser then enter the address to see if it works:
http://localhost:5006/browse

**Comment by chaijinchao** [comment]
Hi, 
 
I enter the address (http://localhost:5006/browse) in the web browser, and it doesn't work.

**Comment by jamescjc123** [comment]
Hi,

I enter the address (http://localhost:5006/browse) in the web browser, and it doesn't work

**Comment by linglingtingfei** [comment]
@JasperYH  I came cross the same problem. I've tried  the solution above, but it didn't work. Do you have better suggestion? I attached the screenshot of error. It seems to be stuck.
![image](https://cloud.githubusercontent.com/assets/20789616/23048591/d85ce71e-f4f1-11e6-8085-0f17f447940a.png)

**Comment by jgoecks** [comment]
This was due to an error in Bokeh ( https://github.com/bokeh/bokeh/issues/6152 ). I've upgraded to the most recent version of Bokeh, which fixes this issue.
